[[{"chat_side":"chat_box right_txt", "chat_color": "whatsapp_chat right_color", "chat": "Hi Grant.", "time": "21:50 pm"},
{"chat_side": "chat_box", "chat_color": "whatsapp_chat", "chat": "Hi Colm. How are you?", "time": "21:50 pm"},
{"chat_side": "chat_box right_txt", "chat_color": "whatsapp_chat right_color", "chat": "Not bad thanks. What about you?", "time": "21:50 pm"},
{"chat_side": "chat_box", "chat_color": "whatsapp_chat", "chat": "Exhausted actually! Can't wait for the holidays.", "time": "21:50 pm"},
{"chat_side": "chat_box right_txt", "chat_color": "whatsapp_chat right_color", "chat": "tell me about it!", "time": "21:50 pm"},
{"chat_side": "chat_box right_txt", "chat_color": "whatsapp_chat right_color", "chat": "Listen I sent you an email earlier. Can you have a gander at it?", "time": "21:50 pm"},
{"chat_side": "chat_box", "chat_color": "whatsapp_chat", "chat": "Sure things mate. I'm a bit tied up at the moment but I'll check it asap.", "time": "21:50 pm"},
{"chat_side": "chat_box right_txt", "chat_color": "whatsapp_chat right_color", "chat": "The main thing is this conference in Germany. Can you give Valerie a berr or drop.", "time": "21:50 pm"}],
[{"chat_side":"chat_box right_txt", "chat_color": "whatsapp_chat right_color", "chat": "Hi Grant.", "time": "21:50 pm"},
{"chat_side": "chat_box", "chat_color": "whatsapp_chat", "chat": "Hi Colm. How are you?", "time": "21:50 pm"},
{"chat_side": "chat_box right_txt", "chat_color": "whatsapp_chat right_color", "chat": "Not bad thanks. What about you?", "time": "21:50 pm"},
{"chat_side": "chat_box", "chat_color": "whatsapp_chat", "chat": "Exhausted actually! Can't wait for the holidays.", "time": "21:50 pm"},
{"chat_side": "chat_box right_txt", "chat_color": "whatsapp_chat right_color", "chat": "tell me about it!", "time": "21:50 pm"},
{"chat_side": "chat_box right_txt", "chat_color": "whatsapp_chat right_color", "chat": "Listen I sent you an email earlier. Can you have a gander at it?", "time": "21:50 pm"},
{"chat_side": "chat_box", "chat_color": "whatsapp_chat", "chat": "Sure things mate. I'm a bit tied up at the moment but I'll check it asap.", "time": "21:50 pm"},
{"chat_side": "chat_box right_txt", "chat_color": "whatsapp_chat right_color", "chat": "The main thing is this conference in Germany. Can you give Valerie a berr or drop.", "time": "21:50 pm"}]]
